[package]
name = "github-reusable-workflows-example-rust"
version = "1.3.31+37"
edition = "2021"
publish = false

[dependencies]
reqwest = "=0.12.25"
tokio = { version = "=1.48.0", features = ["full"] }
