[package]
name = "github-reusable-workflows-example-rust"
version = "1.3.40+46"
edition = "2021"
publish = false

[dependencies]
reqwest = "=0.13.2"
tokio = { version = "=1.49.0", features = ["full"] }
