[package]
name = "github-reusable-workflows-example-rust"
version = "1.3.37+43"
edition = "2021"
publish = false

[dependencies]
reqwest = "=0.13.1"
tokio = { version = "=1.48.0", features = ["full"] }
